// Learn more about Tauri commands at https://tauri.app/develop/calling-rust/
use template_studio_template_core::{render_string, render_tree, TemplateFile, Variables};
use tauri::Manager;
use std::path::{Path, PathBuf};

mod config;

use config::Config;

#[tauri::command]
fn greet(name: &str) -> String {
    format!("Hello, {}! You've been greeted from Rust!", name)
}

/// 最小化窗口
#[tauri::command]
fn window_minimize(app: tauri::AppHandle) {
    let window = app.get_webview_window("main").unwrap();
    window.minimize().unwrap();
}

/// 最大化/还原窗口
#[tauri::command]
fn window_maximize(app: tauri::AppHandle) {
    let window = app.get_webview_window("main").unwrap();
    if window.is_maximized().unwrap() {
        window.unmaximize().unwrap();
    } else {
        window.maximize().unwrap();
    }
}

/// 关闭窗口
#[tauri::command]
fn window_close(app: tauri::AppHandle) {
    let window = app.get_webview_window("main").unwrap();
    window.close().unwrap();
}

/// 获取模板列表
#[tauri::command]
async fn list_templates() -> Result<Vec<Template>, String> {
    // TODO: 从 API 或本地加载模板列表
    // 这里先返回模拟数据
    Ok(vec![
        Template {
            id: "1".to_string(),
            name: "Go Web Service".to_string(),
            description: Some("一个使用 Gin 框架的 Go Web 服务模板".to_string()),
            template_type: "web".to_string(),
            language: Some("Go".to_string()),
            is_featured: true,
        },
        Template {
            id: "2".to_string(),
            name: "Rust CLI Tool".to_string(),
            description: Some("使用 Clap 的 Rust 命令行工具模板".to_string()),
            template_type: "cli".to_string(),
            language: Some("Rust".to_string()),
            is_featured: false,
        },
    ])
}

/// 获取模板变量定义
#[tauri::command]
async fn get_template_variables(template_id: &str) -> Result<Vec<Variable>, String> {
    // TODO: 从 API 或本地加载变量定义
    // 这里先返回模拟数据
    Ok(match template_id {
        "1" => vec![
            Variable {
                name: "project_name".to_string(),
                title: "项目名称".to_string(),
                description: "请输入项目名称".to_string(),
                type_: "string".to_string(),
                default_value: Some("my-project".to_string()),
                required: true,
            },
            Variable {
                name: "author".to_string(),
                title: "作者".to_string(),
                description: "作者名称".to_string(),
                type_: "string".to_string(),
                default_value: Some("Your Name".to_string()),
                required: true,
            },
        ],
        "2" => vec![
            Variable {
                name: "cli_name".to_string(),
                title: "CLI 名称".to_string(),
                description: "命令行工具名称".to_string(),
                type_: "string".to_string(),
                default_value: Some("my-cli".to_string()),
                required: true,
            },
        ],
        _ => vec![],
    })
}

/// 渲染模板预览
#[tauri::command]
fn render_template(
    template_id: String,
    variables: serde_json::Value,
) -> Result<Vec<RenderedFile>, String> {
    let vars = Variables::from_json(&variables.to_string())
        .map_err(|e| e.to_string())?;

    // TODO: 根据 template_id 加载实际模板内容
    // 这里使用模拟的模板内容
    let template_content = match template_id.as_str() {
        "1" => "package main\n\nimport \"fmt\"\n\nfunc main() {\n    fmt.Println(\"Hello, {{ project_name }}!\")\n    fmt.Println(\"Author: {{ author }}\")\n}",
        "2" => "use std::println;\n\nfn main() {\n    println!(\"Hello, {{ cli_name }}!\");\n}",
        _ => "Hello, {{ name }}!"
    };

    // 简单渲染示例（实际应该使用 render_tree）
    let result = render_string(template_content, &vars, None)
        .map_err(|e| e.to_string())?;

    // 返回模拟的文件列表
    Ok(vec![
        RenderedFile {
            path: match template_id.as_str() {
                "1" => "main.go".to_string(),
                "2" => "main.rs".to_string(),
                _ => "main.txt".to_string()
            },
            content: result.content,
        },
        RenderedFile {
            path: "README.md".to_string(),
            content: format!(
                "# Project\n\nGenerated by: {}\n\nWelcome to your new project!",
                variables.get("project_name")
                    .or_else(|| variables.get("cli_name"))
                    .or_else(|| variables.get("name"))
                    .and_then(|v| v.as_str())
                    .unwrap_or("unknown")
            ),
        },
    ])
}

/// 渲染模板预览（返回文件树）
#[tauri::command]
async fn render_template_preview(
    template_id: String,
    variables: serde_json::Value,
    version: Option<String>,
) -> Result<String, String> {
    use template_studio_template_core::{render_tree, TemplateFile, Variables};
    use std::path::Path;

    println!("渲染模板预览:");
    println!("  模板ID: {}", template_id);
    println!("  版本: {:?}", version);

    // 1. 加载配置并获取模板路径
    let config = Config::load().map_err(|e| format!("加载配置失败: {}", e))?;

    // 确定版本号
    let version_str = version.unwrap_or_else(|| {
        // 如果没有指定版本，使用 "latest"
        "latest".to_string()
    });

    let template_path = config.get_template_path(&template_id, &version_str);

    // 检查模板是否存在
    if !template_path.exists() {
        return Err(format!(
            "模板未下载，请先下载模板。路径: {:?}",
            template_path
        ));
    }

    println!("模板路径: {:?}", template_path);

    // 2. 扫描模板文件
    let template_files = scan_template_files(&template_path)
        .map_err(|e| format!("扫描模板文件失败: {}", e))?;

    println!("扫描到 {} 个文件/目录", template_files.len());

    // 3. 准备变量
    let variables_json = serde_json::to_string(&variables)
        .map_err(|e| format!("序列化变量失败: {}", e))?;

    let render_vars = Variables::from_json(&variables_json)
        .map_err(|e| format!("解析变量失败: {}", e))?;

    // 4. 渲染模板树
    let rendered_tree = render_tree(template_files, &render_vars)
        .map_err(|e| format!("渲染模板失败: {}", e))?;

    println!("渲染完成，生成 {} 个文件节点", rendered_tree.len());

    // 5. 序列化为 JSON 返回
    let result_json = serde_json::to_string(&rendered_tree)
        .map_err(|e| format!("序列化结果失败: {}", e))?;

    Ok(result_json)
}

/// 生成项目
#[tauri::command]
async fn generate_project(
    template_id: String,
    variables: serde_json::Value,
    output_path: String,
    version: Option<String>,
) -> Result<String, String> {
    use template_studio_template_core::{render_tree, TemplateFile, Variables};
    use std::fs;
    use std::path::Path;

    println!("生成项目:");
    println!("  模板ID: {}", template_id);
    println!("  输出路径: {}", output_path);
    println!("  版本: {:?}", version);

    // 1. 加载配置并获取模板路径
    let config = Config::load().map_err(|e| format!("加载配置失败: {}", e))?;

    // 确定版本号
    let version_str = version.unwrap_or_else(|| {
        // 如果没有指定版本，使用 "latest"
        "latest".to_string()
    });

    let template_path = config.get_template_path(&template_id, &version_str);

    // 检查模板是否存在
    if !template_path.exists() {
        return Err(format!(
            "模板未下载，请先下载模板。路径: {:?}",
            template_path
        ));
    }

    println!("模板路径: {:?}", template_path);

    // 2. 扫描模板文件
    let template_files = scan_template_files(&template_path)
        .map_err(|e| format!("扫描模板文件失败: {}", e))?;

    println!("扫描到 {} 个文件/目录", template_files.len());

    // 3. 准备变量
    let variables_json = serde_json::to_string(&variables)
        .map_err(|e| format!("序列化变量失败: {}", e))?;

    let render_vars = Variables::from_json(&variables_json)
        .map_err(|e| format!("解析变量失败: {}", e))?;

    // 4. 渲染模板树
    let rendered_tree = render_tree(template_files, &render_vars)
        .map_err(|e| format!("渲染模板失败: {}", e))?;

    println!("渲染完成，生成 {} 个文件节点", rendered_tree.len());

    // 5. 写入文件到输出目录
    let output_dir = Path::new(&output_path);
    let template_path = config.get_template_path(&template_id, &version_str);

    // 如果输出目录已存在，先删除
    if output_dir.exists() {
        fs::remove_dir_all(output_dir)
            .map_err(|e| format!("删除已存在目录失败: {}", e))?;
    }

    // 创建输出目录
    fs::create_dir_all(output_dir)
        .map_err(|e| format!("创建输出目录失败: {}", e))?;

    let mut success_count = 0;
    let mut error_count = 0;
    let mut binary_count = 0;
    let mut _skipped_count = 0;

    for file_node in rendered_tree {
        let file_path = output_dir.join(&file_node.file_path);
        let source_path = template_path.join(&file_node.file_path);

        if let Some(render_error) = file_node.error {
            eprintln!("渲染文件失败: {}", file_node.file_path);
            eprintln!("  错误类型: {}", render_error.error_type);
            eprintln!("  错误信息: {}", render_error.message);
            error_count += 1;
            continue;
        }

        if file_node.is_directory == 1 {
            // 创建目录
            fs::create_dir_all(&file_path)
                .map_err(|e| format!("创建目录 {:?} 失败: {}", file_path, e))?;
        } else {
            // 写入文件
            if let Some(parent) = file_path.parent() {
                if !parent.exists() {
                    fs::create_dir_all(parent)
                        .map_err(|e| format!("创建父目录 {:?} 失败: {}", parent, e))?;
                }
            }

            // 检查文件内容
            match &file_node.file_content {
                Some(content) if !content.is_empty() => {
                    // 有内容：文本文件，写入渲染后的内容
                    fs::write(&file_path, content)
                        .map_err(|e| format!("写入文件 {:?} 失败: {}", file_path, e))?;

                    success_count += 1;
                    println!("创建文件: {}", file_node.file_path);
                }
                _ => {
                    // None 或空字符串：二进制文件或读取失败，直接复制原文件
                    match fs::copy(&source_path, &file_path) {
                        Ok(_) => {
                            binary_count += 1;
                            println!("复制文件: {}", file_node.file_path);
                        }
                        Err(e) => {
                            eprintln!("复制文件失败 {:?} -> {:?}: {}", source_path, file_path, e);
                            error_count += 1;
                        }
                    }
                }
            }
        }
    }

    println!("✅ 项目生成完成!");
    println!("   成功: {} 个文件", success_count);
    if error_count > 0 {
        println!("   失败: {} 个文件", error_count);
    }

    Ok(format!(
        "项目生成成功！路径: {} (成功 {} 个文件)",
        output_path,
        success_count
    ))
}

/// 扫描模板目录，构建文件树
fn scan_template_files(template_path: &Path) -> Result<Vec<TemplateFile>, String> {
    let mut files = Vec::new();
    let mut id_counter = 1i64;

    // 递归扫描模板目录（排除 .meta 目录）
    scan_directory_recursive(template_path, template_path, &mut files, &mut id_counter, 0)?;

    Ok(files)
}

/// 递归扫描目录
fn scan_directory_recursive(
    base_path: &Path,
    dir: &Path,
    files: &mut Vec<TemplateFile>,
    id_counter: &mut i64,
    parent_id: i64,
) -> Result<(), String> {
    use std::fs;

    let entries = fs::read_dir(dir)
        .map_err(|e| format!("读取目录失败 {:?}: {}", dir, e))?;

    for entry in entries {
        let entry = entry.map_err(|e| format!("读取目录项失败: {}", e))?;
        let path = entry.path();

        // 跳过 .meta 目录和 .git 目录
        if path.is_dir() {
            let file_name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("");

            if file_name == ".meta" || file_name == ".git" {
                continue;
            }

            // 创建目录节点
            let relative_path = path
                .strip_prefix(base_path)
                .map_err(|e| format!("计算相对路径失败: {}", e))?;

            let dir_file = TemplateFile {
                id: *id_counter,
                file_path: relative_path.to_string_lossy().replace('\\', "/"),
                file_name: file_name.to_string(),
                file_content: String::new(),
                is_directory: 1,
                parent_id,
                filesize: 0,
                extends: None,
                includes: None,
                imports: None,
                condition: None,
                is_dependency: false,
                required_by: None,
            };

            *id_counter += 1;
            let dir_id = dir_file.id;
            files.push(dir_file);

            // 递归扫描子目录
            scan_directory_recursive(base_path, &path, files, id_counter, dir_id)?;
        } else {
            // 读取文件
            let relative_path = path
                .strip_prefix(base_path)
                .map_err(|e| format!("计算相对路径失败: {}", e))?;

            let metadata = fs::metadata(&path)
                .map_err(|e| format!("获取文件元数据失败 {:?}: {}", path, e))?;

            let file_name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or("")
                .to_string();

            // 检查是否是二进制文件（基于扩展名）
            let extension = path
                .extension()
                .and_then(|s| s.to_str())
                .unwrap_or("")
                .to_lowercase();

            let is_binary = matches!(extension.as_str(),
                "png" | "jpg" | "jpeg" | "gif" | "ico" | "webp" |
                "woff" | "woff2" | "ttf" | "eot" | "otf" |
                "mp3" | "mp4" | "wav" | "ogg" | "webm" |
                "pdf" | "zip" | "exe" | "dll" | "so" |
                "bin" | "dat" | "db" | "sqlite" | "mdb"
            );

            let file_content = if is_binary {
                // 二进制文件：使用空字符串标记（渲染时会跳过，直接复制原文件）
                println!("  [二进制文件] {} - 跳过内容读取", relative_path.display());
                String::new()
            } else {
                // 文本文件：尝试读取内容
                match fs::read_to_string(&path) {
                    Ok(content) => {
                        println!("  [文本文件] {} - {} 字节", relative_path.display(), content.len());
                        content
                    }
                    Err(e) => {
                        // 读取失败，可能是编码问题，记录但继续
                        eprintln!("  [警告] 读取文件失败 {:?}: {}, 将跳过该文件", path, e);
                        String::new()  // 使用空字符串，渲染时会跳过
                    }
                }
            };

            let file = TemplateFile {
                id: *id_counter,
                file_path: relative_path.to_string_lossy().replace('\\', "/"),
                file_name,
                file_content,
                is_directory: 0,
                parent_id,
                filesize: metadata.len() as i32,
                extends: None,
                includes: None,
                imports: None,
                condition: None,
                is_dependency: false,
                required_by: None,
            };

            *id_counter += 1;
            files.push(file);
        }
    }

    Ok(())
}

/// 检查模板版本是否已下载
#[tauri::command]
fn check_template_downloaded(template_id: String, version: String) -> bool {
    use std::path::PathBuf;

    if let Ok(config) = Config::load() {
        let template_path = config.get_template_path(&template_id, &version);
        template_path.exists()
    } else {
        false
    }
}

/// 检查目录是否存在
#[tauri::command]
fn check_directory_exists(path: String) -> bool {
    use std::path::Path;
    Path::new(&path).exists()
}

/// 删除目录（用于覆盖已存在的项目）
#[tauri::command]
fn remove_directory(path: String) -> Result<String, String> {
    use std::path::Path;
    let path = Path::new(&path);

    if path.exists() {
        std::fs::remove_dir_all(path)
            .map_err(|e| format!("删除目录失败: {}", e))?;
        Ok("目录删除成功".to_string())
    } else {
        Ok("目录不存在".to_string())
    }
}

/// 获取配置
#[tauri::command]
fn get_config() -> Result<String, String> {
    let config = Config::load()
        .map_err(|e| format!("加载配置失败: {}", e))?;

    serde_json::to_string(&config)
        .map_err(|e| format!("序列化配置失败: {}", e))
}

/// 更新 Web 服务器配置
#[tauri::command]
fn update_web_server_config(
    api_url: Option<String>,
    api_key: Option<String>,
) -> Result<String, String> {
    let mut config = Config::load()
        .map_err(|e| format!("加载配置失败: {}", e))?;

    // 更新配置
    if let Some(url) = api_url {
        config.web_server.api_url = url;
    }
    if let Some(key) = api_key {
        // 如果传入空字符串，设置为 None
        config.web_server.api_key = if key.is_empty() { None } else { Some(key) };
    }

    // 保存配置
    config.save()
        .map_err(|e| format!("保存配置失败: {}", e))?;

    Ok("配置已保存".to_string())
}

/// 更新模板存储路径
#[tauri::command]
fn update_template_path(template_path: String) -> Result<String, String> {
    use std::path::PathBuf;

    let mut config = Config::load()
        .map_err(|e| format!("加载配置失败: {}", e))?;

    // 验证路径
    let path = PathBuf::from(&template_path);

    // 创建目录（如果不存在）
    std::fs::create_dir_all(&path)
        .map_err(|e| format!("创建模板目录失败: {}", e))?;

    // 更新配置
    config.storage.template_path = path;

    // 保存配置
    config.save()
        .map_err(|e| format!("保存配置失败: {}", e))?;

    Ok("模板存储路径已更新".to_string())
}

/// 获取系统用户名
#[tauri::command]
fn get_username() -> Result<String, String> {
    use std::env;

    // 尝试获取 USER 环境变量
    if let Some(username) = env::var("USER").ok() {
        Ok(username)
    } else if let Some(username) = env::var("USERNAME").ok() {
        Ok(username)
    } else {
        // 如果环境变量都获取不到，尝试使用 dirs 库
        if let Some(home_dir) = dirs::home_dir() {
            if let Some(username_osstr) = home_dir.file_name() {
                if let Some(username_str) = username_osstr.to_str() {
                    return Ok(username_str.to_string());
                }
            }
        }
        Err("无法获取用户名".to_string())
    }
}

/// 下载模板版本到本地
/// 注意：version 参数应该是实际的版本号（如 "1.0.0"）
/// 前端会自动选择 is_latest 的版本，与 CLI 保持完全一致的逻辑
#[tauri::command]
async fn download_template(template_id: String, version: String) -> Result<String, String> {
    use reqwest::Client;
    use std::fs;
    use std::io::Write;

    println!("下载模板: {} 版本: {}", template_id, version);

    // 加载配置
    let config = Config::load().map_err(|e| e.to_string())?;

    // 获取目标路径
    let target_dir = config.get_template_path(&template_id, &version);
    println!("目标路径: {:?}", target_dir);

    // 如果目录已存在，说明已下载
    if target_dir.exists() {
        return Ok(target_dir.to_string_lossy().to_string());
    }

    // 创建目标目录
    fs::create_dir_all(&target_dir).map_err(|e| format!("创建目录失败: {}", e))?;

    // 构建 API URL
    let version_str = if version.is_empty() { "latest".to_string() } else { version.clone() };
    let download_url = format!(
        "{}/api/v1/template/templates/{}/releases/{}/download",
        config.web_server.api_url, template_id, version_str
    );

    println!("下载 URL: {}", download_url);

    // 下载 ZIP 文件
    let client = Client::builder()
        .timeout(std::time::Duration::from_secs(300)) // 5分钟超时
        .build()
        .map_err(|e| format!("创建HTTP客户端失败: {}", e))?;

    let response = client.get(&download_url)
        .send()
        .await
        .map_err(|e| format!("下载请求失败: {}", e))?;

    if !response.status().is_success() {
        return Err(format!("下载失败: HTTP {}", response.status()));
    }

    let zip_bytes = response.bytes().await
        .map_err(|e| format!("读取响应体失败: {}", e))?;

    // 保存为临时 ZIP 文件
    let zip_path = target_dir.join(".temp.zip");
    let mut file = fs::File::create(&zip_path)
        .map_err(|e| format!("创建ZIP文件失败: {}", e))?;
    file.write_all(&zip_bytes)
        .map_err(|e| format!("写入ZIP文件失败: {}", e))?;

    // 解压 ZIP 文件
    println!("解压ZIP文件...");
    let mut archive = zip::ZipArchive::new(fs::File::open(&zip_path)
        .map_err(|e| format!("打开ZIP文件失败: {}", e))?)
        .map_err(|e| format!("读取ZIP存档失败: {}", e))?;

    archive.extract(&target_dir)
        .map_err(|e| format!("解压失败: {}", e))?;

    // 删除临时 ZIP 文件
    fs::remove_file(&zip_path)
        .map_err(|e| format!("删除临时文件失败: {}", e))?;

    println!("模板下载成功: {:?}", target_dir);

    Ok(target_dir.to_string_lossy().to_string())
}

// 数据结构
#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct Template {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub template_type: String,
    pub language: Option<String>,
    pub is_featured: bool,
}

#[derive(serde::Serialize, serde::Deserialize, Clone)]
pub struct Variable {
    pub name: String,
    pub title: String,
    pub description: String,
    pub type_: String,
    pub default_value: Option<String>,
    pub required: bool,
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct RenderedFile {
    pub path: String,
    pub content: String,
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![
            greet,
            window_minimize,
            window_maximize,
            window_close,
            list_templates,
            get_template_variables,
            render_template,
            render_template_preview,
            generate_project,
            check_template_downloaded,
            download_template,
            check_directory_exists,
            remove_directory,
            get_config,
            update_web_server_config,
            update_template_path,
            get_username,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
